services:
  - type: web
    name: shl-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    rootDir: backend

  - type: web
    name: shl-ui
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend/app.py --server.port=8080 --server.address=0.0.0.0
    rootDir: .
